### PR TITLE
pruned redundant paths in control succession search

### PR DESCRIPTION
**Pull request by jcrozum**
This improves the control algorithm and better aligns it with `pystablemotifs`.

### CODE REVIEW

**Comment by jcrozum** [comment]
Just realized that some more pruning might be possible and might be necessary to get things perfectly matched up with `pystablemotifs`. Please hold off on merging until I've had a chance to give it more thought (tomorrow--it's late here and I'm not anywhere near 100% brainpower).

**Comment by jcrozum** [comment]
@daemontus I think this should resolve the main issues we discussed this morning (afternoon for you, I guess). I made the path skipping you implemented is optional, and the option isn't used anywhere (defaults to not use it). I think with your new method to merge the intervention outputs and the improved descendant checking I just added, we should resolve inconsistencies with `pystablemotifs` (except in cases where `pystablemotifs` messes up due to worse percolation, as we discussed).

**Comment by daemontus** [comment]
Thank you!

Your latest changes with the `skip_feedforward_successions` did indeed help quite a bit. We still need to prune the control strategies in the benchmark script because there are sometimes duplicates across different intervention objects. But overall, the new situation is much better.

I believe there might be another problem in pystablemotifs (I'll send more in an email), but there's probably nothing we can do with that.

**Comment by daemontus** [comment]
I've added the fix for "lost" stable motifs. I think we can merge this now.

**Pull request merged**
